# ─────────────────────────────────────────────────────────────────────────────
# VaultKeep ProGuard / R8 Rules
# ─────────────────────────────────────────────────────────────────────────────

# ── R8 Optimization flags ────────────────────────────────────────────────────
# These complement proguard-android-optimize.txt by enabling all R8 passes
-optimizationpasses 5
-allowaccessmodification
-repackageclasses 'vk'

# ── Kotlin ───────────────────────────────────────────────────────────────────
-keepattributes *Annotation*, InnerClasses, Signature, EnclosingMethod
-keepattributes SourceFile, LineNumberTable        # Keep crash stack traces readable
-renamesourcefileattribute SourceFile

# ── Room Database ─────────────────────────────────────────────────────────────
# Protect entity classes so Room can access fields at runtime
-keep class app.istrid.vaultkeep.data.model.** { *; }
# Protect DAO implementations generated by KSP
-keep interface app.istrid.vaultkeep.data.dao.** { *; }
# Room internals
-keep class androidx.room.** { *; }
-dontwarn androidx.room.**

# ── kotlinx.serialization ─────────────────────────────────────────────────────
# Protect serializable data classes used by BackupManager JSON
-keepclassmembers class kotlinx.serialization.json.** { *** Companion; }
-keepclasseswithmembers class * {
    @kotlinx.serialization.Serializable <fields>;
}
-keep @kotlinx.serialization.Serializable class * { *; }
-dontwarn kotlinx.serialization.**

# ── SQLCipher ────────────────────────────────────────────────────────────────
-keep class net.sqlcipher.** { *; }
-keep class net.sqlcipher.database.** { *; }
-dontwarn net.sqlcipher.**

# ── Koin ─────────────────────────────────────────────────────────────────────
-keep class org.koin.** { *; }
-keepnames class * implements org.koin.core.module.Module
-dontwarn org.koin.**

# ── AndroidX Biometric ───────────────────────────────────────────────────────
-keep class androidx.biometric.** { *; }
-dontwarn androidx.biometric.**

# ── Jetpack Compose ──────────────────────────────────────────────────────────
# Compose relies heavily on reflection for @Composable lambdas; keep runtime
-keep class androidx.compose.runtime.** { *; }
-dontwarn androidx.compose.**

# ── Cryptography ─────────────────────────────────────────────────────────────
# Protect our crypto classes from being renamed (JCA reflection references)
-keep class app.istrid.vaultkeep.security.** { *; }

# ── Coroutines ───────────────────────────────────────────────────────────────
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}
-dontwarn kotlinx.coroutines.**

# ── General Android ──────────────────────────────────────────────────────────
-keepclassmembers class * extends android.os.Parcelable {
    public static final ** CREATOR;
}
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
